### ISSUE TITLE
Fluid on Raspberry Pi 2 B1.1 no WLAN

### ISSUE THREAD

**Issue by Flashtony76** [fluidd-core/FluiddPI#16]
Hi,

I am trying to run FluidPi on my Raspberry Pi 2 B1.1.
It does not have WLAN, I connected it to my Router via LanCable in the hopes it would get an IP Adress automatically.
I tried to find Hardware requirements or a LAN setup Guide but failed to do so.

Is my Pi suppported? 
Is it possible to run it in LAN instead of WLAN?

Best Regards
Tony

PS: Sorry for the Issue.

**Comment by ForsakenHarmony** [comment]
Yes, just using Ethernet should work fine, have you run into any issues?

**Comment by matmen** [comment]
@Flashtony76 Do you have any additonal questions or is this solved?
