### ISSUE TITLE
[Question] Data storage location for different hosts

### ISSUE THREAD

**Issue by AndreasReitberger** [fluidd-core/FluiddPI#22]
I'm trying to build a client application to work with Fluidd.
I'm mostly done with the project, however I cannot figure out where FluiddPi stores the different hosts information?

![image](https://user-images.githubusercontent.com/2952443/149615964-cad95023-6014-4a7a-bb73-771050a0f71c.png)

MainsailOS is doing this in the database, however this seems not to be the case for FluiddPi.
Can you give me a hint? I need to get the information via WebSocket or REST-API.

Thank you!

**Comment by matmen** [comment]
Hey, what data are you trying to access specifically?

**Comment by matmen** [comment]
The host addresses aren't available through an API (yet); they are stored in the browser's local storage (`localStorage.appInstances`)

**Comment by matmen** [comment]
I'll go ahead and close this. Feel free to re-open if you need any additional information 🙂
