### ISSUE TITLE
Shutdown does not work after update 

### ISSUE THREAD

**Issue by sanscorp1** [fluidd-core/FluiddPI#23]
I just installer the latest updates including moonraker v0.7.1-343-g305e002 and Fluid v1.16.2 and the host shutdown, reboot or services reboots  stopped working.

It worked flawlessly before, no other updates are performed, running an RPI4 4GB.

**Comment by xerootg** [comment]
try

**Comment by xerootg** [comment]
Well... We should PR a fix. I had the issue, you had the issue, its only
confirmed at this point ;)

**Comment by sanscorp1** [comment]
Only problem is I am unsure if updating the Pi or updating moonraker caused the problem.
