### ISSUE TITLE
OS Package Update Error

### ISSUE THREAD

**Issue by Quickuser75** [fluidd-core/FluiddPI#24]
Hi I am getting an error update the OS packages

Transaction Refresh Cache: Error Failed Run time 0.00 seconds
error updating system

**Comment by matmen** [comment]
Hey, any more logs you can share with us? Is this persistent? What exactly are you doing to get this error, just triggering an update via the web UI?

**Comment by coltenxxx** [comment]
Hello, I'm getting the same exact error. Absolute fresh install of latest Fluidpi on a 32gb sd card flashed via raspi flasher. Got into the webui just fine, and updated all packages via settings. But upon trying to update "os packages" as op mentioned, same exact error.

**Comment by matmen** [comment]
Please try if this fixes it: https://github.com/fluidd-core/fluidd/issues/518#issuecomment-1042243489

**Comment by coltenxxx** [comment]
> 

This fix worked just fine. Ran the code via ssh and then went back to Fluidpi page and tried update again, worked great. Thank you!

**Comment by dohlin** [comment]
Just came here to chime in that I was seeing this exact same issue, and the linked steps resolved it for me as well.  Thank you!!

**Comment by williamrankin** [comment]
I tried creating the image on two different PCs with balenaEtcher on to SanDisk 32GB microSD and both failed the check.
