### ISSUE TITLE
1.17.0v Moonraker warnings.

### ISSUE THREAD

**Issue by ZLXT** [fluidd-core/FluiddPI#26]
Hi,i meet some warnings. I fix one(PolicyKit Permissions) ,but some, i don't know how to fix them.
![image](https://user-images.githubusercontent.com/23455922/155842373-0aa21cc7-eb01-48ab-8b68-86aa1520c37c.png)

**Comment by matmen** [comment]
https://github.com/fluidd-core/fluidd/issues/518#issuecomment-1042243489 should do the trick for you

**Comment by ZLXT** [comment]
Sorry,it still have same problem.
![image](https://user-images.githubusercontent.com/23455922/155842976-5ddb3831-2169-42aa-9f6b-ff34b6fa685d.png)

**Comment by matmen** [comment]
Can you try rebooting the Pi? I'm not sure what else it would be.

**Comment by ZLXT** [comment]
I'm try,but reboot don't wrok,still have same problem.
By the way,when i use v1.16.2,it work normal,i don't meet any problem.Maybe i should use v1.16.2.  :)
This is log:
[moonraker.log](https://github.com/fluidd-core/FluiddPI/files/8146650/moonraker.log)

[klippy.log](https://github.com/fluidd-core/FluiddPI/files/8146647/klippy.log)

**Comment by matmen** [comment]
Downgrading to 1.16.2 doesn't solve the problem, it just hides the notification.
I'm not sure why the fix isn't working for you, it did for everyone else. I'll have to look into this some more.

**Comment by Merkya87** [comment]
Hello I am having the same warnings as well, and have tried the following steps mentioned above
[moonraker.log](https://github.com/fluidd-core/FluiddPI/files/8147273/moonraker.log)
[klippy.log](https://github.com/fluidd-core/FluiddPI/files/8147274/klippy.log)
.

**Comment by Merkya87** [comment]
> sudo apt install packagekit

This worked, thanks!
